#pragma once

namespace mcfile {
namespace biomes {
namespace minecraft {

enum : BiomeId {
    ocean = 1,
    plains,
    desert,
    mountains,
    forest,
    taiga,
    swamp,
    river,
    nether_wastes,
    the_end,
    frozen_ocean,
    frozen_river,
    snowy_tundra,
    snowy_mountains,
    mushroom_fields,
    mushroom_field_shore,
    beach,
    desert_hills,
    wooded_hills,
    taiga_hills,
    mountain_edge,
    jungle,
    jungle_hills,
    jungle_edge,
    deep_ocean,
    stone_shore,
    snowy_beach,
    birch_forest,
    birch_forest_hills,
    dark_forest,
    snowy_taiga,
    snowy_taiga_hills,
    giant_tree_taiga,
    giant_tree_taiga_hills,
    wooded_mountains,
    savanna,
    savanna_plateau,
    badlands,
    wooded_badlands_plateau,
    badlands_plateau,
    small_end_islands,
    end_midlands,
    end_highlands,
    end_barrens,
    warm_ocean,
    lukewarm_ocean,
    cold_ocean,
    deep_warm_ocean,
    deep_lukewarm_ocean,
    deep_cold_ocean,
    deep_frozen_ocean,
    the_void,
    sunflower_plains,
    desert_lakes,
    gravelly_mountains,
    flower_forest,
    taiga_mountains,
    swamp_hills,
    ice_spikes,
    modified_jungle,
    modified_jungle_edge,
    tall_birch_forest,
    tall_birch_hills,
    dark_forest_hills,
    snowy_taiga_mountains,
    giant_spruce_taiga,
    giant_spruce_taiga_hills,
    modified_gravelly_mountains,
    shattered_savanna,
    shattered_savanna_plateau,
    eroded_badlands,
    modified_wooded_badlands_plateau,
    modified_badlands_plateau,
    bamboo_jungle,
    bamboo_jungle_hills,

    // 20w06a
    soul_sand_valley,
    crimson_forest,
    warped_forest,

    // 20w15a
    basalt_deltas,

    minecraft_max_biome_id,
};

} // namespace minecraft
} // namespace biomes
} // namespace mcfile
