#pragma once

namespace mcfile::be {

class Block {
public:
    Block(std::u8string const &name, std::shared_ptr<nbt::CompoundTag> const &states, std::optional<int32_t> version, std::optional<int16_t> val = std::nullopt)
        : fName(name)
        , fVersion(version)
        , fVal(val) {
        if (states) {
            fStates = states;
        } else {
            fStates = std::make_shared<nbt::CompoundTag>();
        }
    }

    static std::shared_ptr<Block> FromCompound(nbt::CompoundTag const &tag) {
        auto name = tag.string(u8"name");
        auto states = tag.compoundTag(u8"states");
        auto version = tag.int32(u8"version");
        if (!name) {
            return nullptr;
        }
        auto val = tag.int16(u8"val");
        return std::make_shared<Block>(*name, states, version, val);
    }

    std::shared_ptr<nbt::CompoundTag> toCompoundTag() const {
        using namespace std;
        auto tag = make_shared<nbt::CompoundTag>();
        tag->set(u8"name", make_shared<nbt::StringTag>(fName));
        if (fVal && !fVersion) {
            tag->set(u8"val", make_shared<nbt::ShortTag>(*fVal));
        } else {
            tag->set(u8"states", fStates->clone());
            tag->set(u8"version", make_shared<nbt::IntTag>(*fVersion));
        }
        return tag;
    }

    static std::u8string BlockNameById(uint8_t id) {
        static std::array<std::u8string, 256> const sTable = {
            u8"minecraft:air",
            u8"minecraft:stone",
            u8"minecraft:grass",
            u8"minecraft:dirt",
            u8"minecraft:cobblestone",
            u8"minecraft:planks",
            u8"minecraft:sapling",
            u8"minecraft:bedrock",
            u8"minecraft:flowing_water",
            u8"minecraft:water",
            u8"minecraft:flowing_lava",
            u8"minecraft:lava",
            u8"minecraft:sand",
            u8"minecraft:gravel",
            u8"minecraft:gold_ore",
            u8"minecraft:iron_ore",
            u8"minecraft:coal_ore",
            u8"minecraft:log",
            u8"minecraft:leaves",
            u8"minecraft:sponge",
            u8"minecraft:glass",
            u8"minecraft:lapis_ore",
            u8"minecraft:lapis_block",
            u8"minecraft:dispenser",
            u8"minecraft:sandstone",
            u8"minecraft:noteblock",
            u8"minecraft:bed",
            u8"minecraft:golden_rail",
            u8"minecraft:detector_rail",
            u8"minecraft:sticky_piston",
            u8"minecraft:web",
            u8"minecraft:tallgrass",
            u8"minecraft:deadbush",
            u8"minecraft:piston",
            u8"minecraft:pistonArmCollision",
            u8"minecraft:wool",
            u8"minecraft:element_0",
            u8"minecraft:yellow_flower",
            u8"minecraft:red_flower",
            u8"minecraft:brown_mushroom",
            u8"minecraft:red_mushroom",
            u8"minecraft:gold_block",
            u8"minecraft:iron_block",
            u8"minecraft:double_stone_slab",
            u8"minecraft:stone_slab",
            u8"minecraft:brick_block",
            u8"minecraft:tnt",
            u8"minecraft:bookshelf",
            u8"minecraft:mossy_cobblestone",
            u8"minecraft:obsidian",
            u8"minecraft:torch",
            u8"minecraft:fire",
            u8"minecraft:mob_spawner",
            u8"minecraft:oak_stairs",
            u8"minecraft:chest",
            u8"minecraft:redstone_wire",
            u8"minecraft:diamond_ore",
            u8"minecraft:diamond_block",
            u8"minecraft:crafting_table",
            u8"minecraft:wheat",
            u8"minecraft:farmland",
            u8"minecraft:furnace",
            u8"minecraft:lit_furnace",
            u8"minecraft:standing_sign",
            u8"minecraft:wooden_door",
            u8"minecraft:ladder",
            u8"minecraft:rail",
            u8"minecraft:stone_stairs",
            u8"minecraft:wall_sign",
            u8"minecraft:lever",
            u8"minecraft:stone_pressure_plate",
            u8"minecraft:iron_door",
            u8"minecraft:wooden_pressure_plate",
            u8"minecraft:redstone_ore",
            u8"minecraft:lit_redstone_ore",
            u8"minecraft:redstone_torch",
            u8"minecraft:redstone_torch",
            u8"minecraft:stone_button",
            u8"minecraft:snow_layer",
            u8"minecraft:ice",
            u8"minecraft:snow",
            u8"minecraft:cactus",
            u8"minecraft:clay",
            u8"minecraft:reeds",
            u8"minecraft:jukebox",
            u8"minecraft:fence",
            u8"minecraft:pumpkin",
            u8"minecraft:netherrack",
            u8"minecraft:soul_sand",
            u8"minecraft:glowstone",
            u8"minecraft:portal",
            u8"minecraft:lit_pumpkin",
            u8"minecraft:cake",
            u8"minecraft:unpowered_repeater",
            u8"minecraft:unpowered_repeater",
            u8"minecraft:invisibleBedrock",
            u8"minecraft:trapdoor",
            u8"minecraft:monster_egg",
            u8"minecraft:stonebrick",
            u8"minecraft:brown_mushroom_block",
            u8"minecraft:red_mushroom_block",
            u8"minecraft:iron_bars",
            u8"minecraft:glass_pane",
            u8"minecraft:melon_block",
            u8"minecraft:pumpkin_stem",
            u8"minecraft:melon_stem",
            u8"minecraft:vine",
            u8"minecraft:fence_gate",
            u8"minecraft:brick_stairs",
            u8"minecraft:stone_brick_stairs",
            u8"minecraft:mycelium",
            u8"minecraft:waterlily",
            u8"minecraft:nether_brick",
            u8"minecraft:nether_brick_fence",
            u8"minecraft:nether_brick_stairs",
            u8"minecraft:nether_wart",
            u8"minecraft:enchanting_table",
            u8"minecraft:brewing_stand",
            u8"minecraft:cauldron",
            u8"minecraft:end_portal",
            u8"minecraft:end_portal_frame",
            u8"minecraft:end_stone",
            u8"minecraft:dragon_egg",
            u8"minecraft:redstone_lamp",
            u8"minecraft:redstone_lamp",
            u8"minecraft:dropper",
            u8"minecraft:activator_rail",
            u8"minecraft:cocoa",
            u8"minecraft:sandstone_stairs",
            u8"minecraft:emerald_ore",
            u8"minecraft:ender_chest",
            u8"minecraft:tripwire_hook",
            u8"minecraft:tripWire",
            u8"minecraft:emerald_block",
            u8"minecraft:spruce_stairs",
            u8"minecraft:birch_stairs",
            u8"minecraft:jungle_stairs",
            u8"minecraft:command_block",
            u8"minecraft:beacon",
            u8"minecraft:cobblestone_wall",
            u8"minecraft:flower_pot",
            u8"minecraft:carrots",
            u8"minecraft:potatoes",
            u8"minecraft:wooden_button",
            u8"minecraft:skull",
            u8"minecraft:anvil",
            u8"minecraft:trapped_chest",
            u8"minecraft:light_weighted_pressure_plate",
            u8"minecraft:heavy_weighted_pressure_plate",
            u8"minecraft:unpowered_comparator",
            u8"minecraft:powered_comparator",
            u8"minecraft:daylight_detector",
            u8"minecraft:redstone_block",
            u8"minecraft:quartz_ore",
            u8"minecraft:hopper",
            u8"minecraft:quartz_block",
            u8"minecraft:quartz_stairs",
            u8"minecraft:double_wooden_slab",
            u8"minecraft:wooden_slab",
            u8"minecraft:stained_hardened_clay",
            u8"minecraft:stained_glass_pane",
            u8"minecraft:leaves2",
            u8"minecraft:log2",
            u8"minecraft:acacia_stairs",
            u8"minecraft:dark_oak_stairs",
            u8"minecraft:slime",
            u8"minecraft:glow_stick",
            u8"minecraft:iron_trapdoor",
            u8"minecraft:prismarine",
            u8"minecraft:seaLantern",
            u8"minecraft:hay_block",
            u8"minecraft:carpet",
            u8"minecraft:hardened_clay",
            u8"minecraft:coal_block",
            u8"minecraft:packed_ice",
            u8"minecraft:double_plant",
            u8"minecraft:standing_banner",
            u8"minecraft:wall_banner",
            u8"minecraft:daylight_detector_inverted",
            u8"minecraft:red_sandstone",
            u8"minecraft:red_sandstone_stairs",
            u8"minecraft:double_stone_slab2",
            u8"minecraft:stone_slab2",
            u8"minecraft:spruce_fence_gate",
            u8"minecraft:birch_fence_gate",
            u8"minecraft:jungle_fence_gate",
            u8"minecraft:dark_oak_fence_gate",
            u8"minecraft:acacia_fence_gate",
            u8"minecraft:repeating_command_block",
            u8"minecraft:chain_command_block",
            u8"minecraft:hard_glass_pane",
            u8"minecraft:hard_stained_glass_pane",
            u8"minecraft:chemical_heat",
            u8"minecraft:spruce_door",
            u8"minecraft:birch_door",
            u8"minecraft:jungle_door",
            u8"minecraft:acacia_door",
            u8"minecraft:dark_oak_door",
            u8"minecraft:grass_path",
            u8"minecraft:frame",
            u8"minecraft:chorus_flower",
            u8"minecraft:purpur_block",
            u8"minecraft:colored_torch_rg",
            u8"minecraft:purpur_stairs",
            u8"minecraft:colored_torch_bp",
            u8"minecraft:undyed_shulker_box",
            u8"minecraft:end_bricks",
            u8"minecraft:frosted_ice",
            u8"minecraft:end_rod",
            u8"minecraft:end_gateway",
            u8"minecraft:210",
            u8"minecraft:211",
            u8"minecraft:212",
            u8"minecraft:magma",
            u8"minecraft:nether_wart_block",
            u8"minecraft:red_nether_brick",
            u8"minecraft:bone_block",
            u8"minecraft:217",
            u8"minecraft:shulker_box",
            u8"minecraft:purple_glazed_terracotta",
            u8"minecraft:white_glazed_terracotta",
            u8"minecraft:orange_glazed_terracotta",
            u8"minecraft:magenta_glazed_terracotta",
            u8"minecraft:light_blue_glazed_terracotta",
            u8"minecraft:yellow_glazed_terracotta",
            u8"minecraft:lime_glazed_terracotta",
            u8"minecraft:pink_glazed_terracotta",
            u8"minecraft:gray_glazed_terracotta",
            u8"minecraft:silver_glazed_terracotta",
            u8"minecraft:cyan_glazed_terracotta",
            u8"minecraft:230",
            u8"minecraft:blue_glazed_terracotta",
            u8"minecraft:brown_glazed_terracotta",
            u8"minecraft:green_glazed_terracotta",
            u8"minecraft:red_glazed_terracotta",
            u8"minecraft:black_glazed_terracotta",
            u8"minecraft:concrete",
            u8"minecraft:concretePowder",
            u8"minecraft:chemistry_table",
            u8"minecraft:underwater_torch",
            u8"minecraft:chorus_plant",
            u8"minecraft:stained_glass",
            u8"minecraft:242",
            u8"minecraft:podzol",
            u8"minecraft:beetroot",
            u8"minecraft:stonecutter",
            u8"minecraft:glowingobsidian",
            u8"minecraft:netherreactor",
            u8"minecraft:info_update",
            u8"minecraft:info_update2",
            u8"minecraft:movingBlock",
            u8"minecraft:observer",
            u8"minecraft:structure_block",
            u8"minecraft:hard_glass",
            u8"minecraft:hard_stained_glass",
            u8"minecraft:reserved6",
        };
        return sTable[id];
    }

public:
    std::u8string fName;
    std::shared_ptr<nbt::CompoundTag> fStates;
    std::optional<int32_t> fVersion;
    std::optional<int16_t> fVal;
};

} // namespace mcfile::be
